language: node_js
sudo: false
node_js:
  - '4.3'
  - '4.4'
  - '5.10'

cache:
  directories:
    - $(npm root -g)

branches:
  only:
    - master
    - dev
    - stage
    - test
    - update_test

before_install:
  - cp bin/test/package.json .
  - npm run prepare

after_success:
  - npm run coverage

